url: https://armmbed.github.io
baseurl: /mbedos-error/

# Site settings
title: mbedos-error
email: support@mbed.com
description: "Mbed OS error decoder"

# Build settings
markdown: kramdown
permalink: pretty
